const container = document.querySelector('#listings');
const dateFormatter = new Intl.DateTimeFormat('en-CA', {timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'});
const today = dateFormatter.format(new Date());
let picks = [], filter = 'all', shelfTimer = null;
let saved;
try { const value=JSON.parse(localStorage.getItem('comedy-saved')||'[]'); saved=new Set(Array.isArray(value)?value:[]); } catch {saved=new Set();}
const element=(tag,text,className)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
function safeURL(value){try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function dateLabel(day){return new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',weekday:'long',month:'long',day:'numeric'}).format(new Date(day+'T12:00:00-04:00'));}
function isWeekend(day){const d=new Date(day+'T12:00:00Z');const current=new Date(today+'T12:00:00Z');const weekday=current.getUTCDay();const start=new Date(current);start.setUTCDate(start.getUTCDate()+(weekday===0?-2:weekday===6?-1:5-weekday));const end=new Date(start);end.setUTCDate(end.getUTCDate()+2);return d>=start&&d<=end;}
function poster(pick,withCredit=true){
 if(!pick.poster || !/^\/assets\/posters\/[a-z0-9.-]+$/.test(pick.poster.src))return null;
 const figure=element('figure',undefined,'show-flyer');
 const link=element('a');link.href=pick.poster.src;link.target='_blank';link.rel='noopener';link.setAttribute('aria-label','Open full poster for '+pick.title);
 const img=element('img');img.src=pick.poster.src;img.alt=pick.poster.alt||('Promotional artwork for '+pick.title);img.width=pick.poster.width;img.height=pick.poster.height;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>figure.remove(),{once:true});link.append(img);figure.append(link);
 if(withCredit){const source=safeURL(pick.poster.source_url);if(source){const credit=element('figcaption');const a=element('a',pick.poster.credit||'Poster source');a.href=source;a.target='_blank';a.rel='noopener noreferrer';credit.append(a);figure.append(credit);}}
 return figure;
}
function ticketLink(pick){const url=safeURL(pick.ticket_url);if(!url)return null;const a=element('a',pick.link_label||'Tickets & details ↗');a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.setAttribute('aria-label',(pick.link_label?'Event listing for ':'Tickets and details for ')+pick.title);return a;}
function render(){
 const focusedSave=document.activeElement?.dataset.saveId;
 container.replaceChildren();
 const now=Date.now(),area=document.querySelector('#neighborhood')?.value;
 const upcoming=picks.filter(p=>Date.parse(p.ends_at)>now).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
 const visible=upcoming.filter(p=>(!area||p.neighborhood===area)&&(filter==='all'||filter==='tonight'&&p.date===today||filter==='weekend'&&isWeekend(p.date)||filter==='cheap'&&Number.isFinite(p.price_amount)&&p.price_amount<=15||filter==='saved'&&saved.has(p.id)));
 const count=document.querySelector('#result-count');if(count)count.textContent=visible.length+' upcoming '+(visible.length===1?'show':'shows')+(area?' · '+area:' · '+new Set(visible.map(p=>p.neighborhood)).size+' '+(new Set(visible.map(p=>p.neighborhood)).size===1?'neighborhood':'neighborhoods'));
 const status=document.querySelector('#board-status');if(status){const dates=[...new Set(upcoming.map(p=>p.verified_at).filter(Boolean))].sort();status.textContent=(dates.length?'Sources checked '+dates[0]+(dates.length>1?'–'+dates.at(-1):'')+'. ':'')+'New York local times. Check ticket pages for updates.';}
 const rooms=document.querySelector('#room-list');if(rooms){rooms.replaceChildren();const grouped=new Map();for(const p of upcoming){const row=grouped.get(p.venue)||{count:0,area:p.neighborhood};row.count++;grouped.set(p.venue,row);}for(const [name,data]of [...grouped].sort((a,b)=>a[0].localeCompare(b[0]))){const li=element('li');const a=element('a',name);a.href='/neighborhoods.html?area='+encodeURIComponent(data.area);li.append(a,element('span',data.count+' '+(data.count===1?'show':'shows')+' · '+data.area,'room-detail'));rooms.append(li);}}
 const board=document.querySelector('#featured-board');if(board){clearInterval(shelfTimer);board.replaceChildren();const ranked=visible.filter(p=>p.poster).sort((a,b)=>Number(Boolean(b.sponsored))-Number(Boolean(a.sponsored))||Number(Boolean(b.featured))-Number(Boolean(a.featured))||a.starts_at.localeCompare(b.starts_at));const pool=[];const left=[...ranked];while(left.length){const recent=pool.slice(-2).map(p=>p.venue);let i=left.findIndex(p=>!recent.includes(p.venue));if(i<0)i=0;pool.push(left.splice(i,1)[0]);}board.hidden=!pool.length;if(pool.length){board.append(element('h2','Pinned to the board','board-heading'));const shelf=element('div',undefined,'flyer-shelf');const slots=Math.min(3,pool.length);const fill=(card,p)=>{card.replaceChildren();card.dataset.id=p.id;const image=poster(p);if(image)card.append(image);const pinDate=element('p',dateLabel(p.date).replace(', September',' · Sep')+' · '+p.time_label,'pin-date');if(p.demand==='sold_out')pinDate.append(element('span','Sold out','demand-tag sold-out'));else if(p.demand==='going_fast')pinDate.append(element('span','Going fast','demand-tag'));card.append(pinDate,element('h3',p.title),element('p',p.venue,'pin-venue'));const ticket=ticketLink(p);if(ticket)card.append(ticket);};const cards=[];for(let i=0;i<slots;i++){const card=element('article',undefined,'pinned-pick');fill(card,pool[i]);shelf.append(card);cards.push(card);}board.append(shelf);
 if(pool.length>slots){let cursor=slots,slot=0;const still=matchMedia('(prefers-reduced-motion: reduce)').matches;shelfTimer=setInterval(()=>{if(document.hidden||shelf.matches(':hover')||shelf.matches(':focus-within'))return;const shown=new Set(cards.map(c=>c.dataset.id));let p;for(let tries=0;tries<pool.length;tries++){const candidate=pool[cursor%pool.length];cursor++;if(!shown.has(candidate.id)){p=candidate;break;}}if(!p)return;const card=cards[slot];slot=(slot+1)%slots;if(still){fill(card,p);return;}card.classList.add('is-leaving');setTimeout(()=>{fill(card,p);card.classList.remove('is-leaving');card.classList.add('is-entering');setTimeout(()=>card.classList.remove('is-entering'),700);},450);},6000);}}}
 const horizon=new Date(new Date(today+'T12:00:00Z').getTime()+14*86400000).toISOString().slice(0,10);const later=document.querySelector('#later'),saveSection=document.querySelector('#save-the-date');const boardPicks=later?visible.filter(p=>p.date<=horizon):visible;const laterPicks=later?visible.filter(p=>p.date>horizon):[];
 if(later){later.replaceChildren();let ld,ls;for(const pick of laterPicks){if(ld!==pick.date){ld=pick.date;ls=element('section',undefined,'day');ls.append(element('h3',dateLabel(ld)));later.append(ls);}const li=element('article',undefined,'pick listing-row later-row');li.id='show-'+pick.id;const b=element('div',undefined,'listing-body');const tl=element('p',pick.time_label,'pick-time');if(pick.demand==='sold_out')tl.append(element('span','Sold out','demand-tag sold-out'));else if(pick.demand==='going_fast')tl.append(element('span','Going fast','demand-tag'));b.append(tl,element('h4',pick.title,'pick-title'),element('p',pick.venue+' · '+pick.neighborhood+' · '+pick.price_label,'pick-detail'));const t=ticketLink(pick);if(t){const a=element('div',undefined,'pick-actions');a.append(t);b.append(a);}li.append(b);ls.append(li);}if(saveSection)saveSection.hidden=!laterPicks.length;}
 if(!boardPicks.length){const box=element('div',undefined,'empty');box.append(element('h3',filter==='saved'?'Your saved picks will show up here.':filter==='tonight'?'Nothing else on our list tonight.':'No upcoming picks in this selection.'),(()=>{const p=element('p');if(filter==='saved'){p.textContent='Use “Save” on a pick to keep it on this device.';}else if(area){p.append('No dated picks there this week. ');const a=element('a','See the rooms and mics in '+area+' →');a.href='/neighborhoods.html?area='+encodeURIComponent(area);p.append(a);}else p.textContent='Try all picks, or check back for the next edition.';return p;})());container.append(box);return;}
 let day,section;
 for(const pick of boardPicks){
  if(day!==pick.date){day=pick.date;section=element('section',undefined,'day');section.append(element('h3',dateLabel(day)));container.append(section);}
  const article=element('article',undefined,'pick listing-row');article.id='show-'+pick.id;
  const landscape=pick.poster&&Number(pick.poster.width)>Number(pick.poster.height);const art=poster(pick,false);if(art){art.classList.add('listing-thumb');if(landscape)art.classList.add('landscape');article.append(art);}
  const body=element('div',undefined,'listing-body');const timeLine=element('p',pick.time_label,'pick-time');if(pick.demand==='sold_out')timeLine.append(element('span','Sold out','demand-tag sold-out'));else if(pick.demand==='going_fast')timeLine.append(element('span','Going fast','demand-tag'));body.append(timeLine,element('h4',pick.title,'pick-title'),element('p',pick.description,'pick-description'));
  const details=element('p',undefined,'pick-detail');details.append(document.createTextNode(pick.venue+' · '+pick.neighborhood+' · '),element('span',pick.price_label,'price-tag'));body.append(details);
  const actions=element('div',undefined,'pick-actions'),ticket=ticketLink(pick);if(ticket)actions.append(ticket);
  if(pick.poster){const source=safeURL(pick.poster.source_url);if(source){const credit=element('a','Flyer source');credit.href=source;credit.target='_blank';credit.rel='noopener noreferrer';credit.className='flyer-credit';actions.append(credit);}}
  const save=element('button',saved.has(pick.id)?'Saved ✓':'Save','save');save.type='button';save.dataset.saveId=pick.id;save.setAttribute('aria-label',(saved.has(pick.id)?'Unsave ':'Save ')+pick.title);save.setAttribute('aria-pressed',String(saved.has(pick.id)));save.addEventListener('click',()=>{saved.has(pick.id)?saved.delete(pick.id):saved.add(pick.id);try{localStorage.setItem('comedy-saved',JSON.stringify([...saved]));}catch{}render();});actions.append(save);body.append(actions);article.append(body);section.append(article);
 }
 if(focusedSave){[...container.querySelectorAll('[data-save-id]')].find(b=>b.dataset.saveId===focusedSave)?.focus();}
}
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render();}));
Promise.all([fetch('/data/picks.json').then(r=>{if(!r.ok)throw Error('Could not load picks');return r.json();}),fetch('/data/venues.json').then(r=>r.ok?r.json():[]).catch(()=>[])]).then(([data,venues])=>{if(!Array.isArray(data))throw Error('Invalid picks');const area=new Map((Array.isArray(venues)?venues:[]).map(v=>[v.name,v.neighborhood]));picks=data.map(p=>({...p,neighborhood:area.get(p.venue)||p.neighborhood}));const select=document.querySelector('#neighborhood');if(select){const boroughs=['Manhattan','Brooklyn','Queens','Bronx','Staten Island'];const list=Array.isArray(venues)?venues:[];const withPicks=new Set(picks.map(p=>p.neighborhood));for(const b of boroughs){const names=[...new Set(list.filter(v=>v.borough===b).map(v=>v.neighborhood))].sort();if(!names.length)continue;const group=document.createElement('optgroup');group.label=b;for(const name of names){const option=element('option',name+(withPicks.has(name)?'':' · rooms only'));option.value=name;group.append(option);}select.append(group);}[...new Set(picks.map(p=>p.neighborhood))].filter(n=>!list.some(v=>v.neighborhood===n)).sort().forEach(name=>{const option=element('option',name);option.value=name;select.append(option);});const area=new URLSearchParams(location.search).get('area');if([...select.options].some(o=>o.value===area))select.value=area;select.addEventListener('change',render);}render();}).catch(()=>{container.replaceChildren(element('p','The picks couldn’t load. Please refresh, or try again shortly.','empty'));});
